### ISSUE TITLE
Unexpected thermal evolution with finer meshes

### ISSUE THREAD

**Issue by stvdwtt** [adamantine-sim/adamantine#139]
I'm seeing an odd bug using the current master branch of the code. For coarse meshes, the code behaves as expected. For somewhat finer meshes, the temperature at the external boundaries is frozen at the initial temperature, but the temperature inside the bulk of the material evolves "normally". For even finer meshes, the entire domain remains frozen at the initial temperature.

This issue appears to be related to the absolute size of the elements, with issues arising once they fall below ~5e-5. Changing between adiabatic and non-adiabatic BCs has no effect.

An example of an input file that triggers this issue is below (with the input file given an extra ".txt" extension so that GitHub lets me attached it). As is, there is evolution in the bulk but the boundary values are frozen. If `length_divisions` and `width_divisions` are changed to 8, the simulation proceeds as normal. If they are changed to 32, then the entire solution is frozen.

[bare_plate_L_scan_path.txt](https://github.com/adamantine-sim/adamantine/files/7961430/bare_plate_L_scan_path.txt)
[bare_plate_unaugmented_ref.info.txt](https://github.com/adamantine-sim/adamantine/files/7961433/bare_plate_unaugmented_ref.info.txt)

Could this be due to misapplied constraints?

**Comment by Rombur** [comment]
Fixed by #140
