### ISSUE TITLE
Nonfunctional EXODUS support

### ISSUE THREAD

**Issue by stvdwtt** [adamantine-sim/adamantine#147]
To quote from @Rombur from #146:

_...there is clash because both SEACAS and ADOL-C have defined the same macro. Right now what happens is that deal.II detects that both SEACAS and ADOL-C are enabled and the configuration fails. Moving forward, we will only use Sacado and we won't need to install ADOL-C. Removing the need to enable all the backends is a WIP (see https://github.com/jppelteret/dealii-weak_forms/pull/46). I am hoping that we get this fixed soonish._

**Comment by jppelteret** [comment]
For more background, see the [comment added](https://github.com/dealii/dealii/commit/79ec2deb58aa810b9a2889216abbbe994a1a41a4#diff-cc3e41cf7781ca97cf9693c0f8f7fe216ab992fc79b5d049166a8e77f0950cf2R50-R54) as a part of https://github.com/dealii/dealii/pull/8200:
```
We have to avoid a symbol clash with Trilinos' SEACASChaco library
(the libchaco.so shared object exports the global symbol 'divide' but
so does adolc itself).
```
This lead to some really strange segfaults, which was a terrible task to debug.
