### ISSUE TITLE
Modify experimental_data to allow reading data as its needed instead of up front

### ISSUE THREAD

**Issue by stvdwtt** [adamantine-sim/adamantine#161]
Currently, the experimental data functions assume that all experimental data is available at the start of the simulation. For real-time data assimilation we need to be able to parse new frames as they become available. Therefore frames need to be parsed one-by-one and we may have to tweak the user interface (e.g. to allow an expected cadence of one experimental frame every X simulated seconds).

**Comment by Rombur** [comment]
Done in #228
