### ISSUE TITLE
Handle case where mechanics is activated in the input file but adamantine isn't compiled with dealii weak forms

### ISSUE THREAD

**Issue by stvdwtt** [adamantine-sim/adamantine#210]
The current behavior is to silently run a thermal-only simulation. At the very least I think we want a warning message, but I think we want the simulation to abort.

**Comment by Rombur** [comment]
It should be pretty easy to add a check [here](https://github.com/adamantine-sim/adamantine/blob/master/source/validate_input_database.cc#L21-L27)

**Comment by stvdwtt** [comment]
Fixed in #209
