### ISSUE TITLE
Issue with material deposition in parallel

### ISSUE THREAD

**Issue by stvdwtt** [adamantine-sim/adamantine#247]
In series material deposition happens as expected. However in parallel some of the mesh is not activated as expected.

Serial:
![image](https://github.com/adamantine-sim/adamantine/assets/10517751/de1496ef-e878-4967-a06d-af1649937aa0)

2 MPI processes:
![image](https://github.com/adamantine-sim/adamantine/assets/10517751/0e4fc41c-0d2f-478b-aeb2-92404903e62c)

4 MPI processes:
![image](https://github.com/adamantine-sim/adamantine/assets/10517751/0f979d9d-470b-475e-a7dd-1904d3455eb7)

h/t Ashley Gannon

**Comment by Rombur** [comment]
Can you post the partitioning? It's the `subdomain_id` plot

**Comment by stvdwtt** [comment]
The material is only being deposited in the subdomain for MPI process 0:
![image](https://github.com/adamantine-sim/adamantine/assets/10517751/2072e563-972b-4fe1-92ea-0dc317299b71)

**Comment by Rombur** [comment]
Can  you share your input files. I tried to reproduce the problem by modifying one of our test but it works as expected.

**Comment by stvdwtt** [comment]
Here you go:
[inputs.zip](https://github.com/adamantine-sim/adamantine/files/12819435/inputs.zip)

**Comment by Rombur** [comment]
The code crashes for me in parallel when using your input files. I assume that you are running in release mode and that's why the code keeps running

**Comment by Rombur** [comment]
I have a fix. I'll open a PR soon.
