### ISSUE TITLE
Bug introduced in #270 for imported meshes

### ISSUE THREAD

**Issue by stvdwtt** [adamantine-sim/adamantine#278]
After #270 neither the hourglass demonstration case nor the Okuma curved wall demonstration case work anymore. Both hang somewhere during initialization.

We should have an integration test with an imported mesh to catch this type of issue.

**Comment by stvdwtt** [comment]
@Rombur, I did, although it's possible that I missed something. I'm planning to look into it more next week.

**Comment by Rombur** [comment]
If you run in debug mode inside of gdb, when you kill the code using `ctrl-c` you can print the backtrace and see exactly where the code is hanging.

**Comment by stvdwtt** [comment]
I think this was an agglomeration of bugs that were fixed and user error.
