### ISSUE TITLE
Unexpected NANs in `_plastic_internal_variable`

### ISSUE THREAD

**Issue by stvdwtt** [adamantine-sim/adamantine#332]
Is this block of `push_back`s correct? It seems like it should be in one of the `else` blocks.

https://github.com/adamantine-sim/adamantine/blob/56fe8b15fe2bb413129a03c39b9dfa136639873e/source/MechanicalPhysics.cc#L351

With the current `master` branch NANs show up in the stress (I believe from `_plastic_internal_variable`), even on a single MPI task.

![image](https://github.com/user-attachments/assets/10a9d7cd-cfe6-4ef8-9aa6-dc566a21de17)

I don't think any of our tests include plasticity, which is why this doesn't show up. The displacement looks fine.

**Comment by Rombur** [comment]
The entire block https://github.com/adamantine-sim/adamantine/blob/56fe8b15fe2bb413129a03c39b9dfa136639873e/source/MechanicalPhysics.cc#L351-L356

should be moved in the `else` just above

**Comment by masterleinad** [comment]
> The entire block should be moved in the else above and duplicate for non locally owned cells.

Agreed.

**Comment by stvdwtt** [comment]
Fixed in #333
